<?php
/**
 * Implements hook_theme().
 */
function bonnie_theme() {
  return [
    'bonnie_template' => [
      'variables' => [
        'title' => NULL,
        'form' => NULL,
        'bonnie' => NULL,
        'DeleteBonnieForm' => NULL,
        'EditForm' => NULL,
      ],
    ],
    'bonnie-items' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
    'cat-structure-table' => [
      'variables' => [
        'items' => NULL,
        'DeleteBonnieForm' => NULL,
        'EditForm' => NULL,
        'DeleteAllBonnieForm' => NULL,
      ],
    ]
  ];
}
